title: Isaac Adewumi's Blog
email: ienioladewumi@gmail.com
description: >-
   Welcome here! I intend to use this to document my thoughts, share learnings and other things that should probably be tweets(or xes).
baseurl: ""
url: "https://eniola.wtf"
twitter_link: https://www.twitter.com/eniolawtf
github_link:  https://www.github.com/prettyirrelevant
linkedin_link: https://www.linkedin.com/in/isaac-adewumi

plugins:
  - jekyll-toc
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-og-image

toc:
  list_id: toc
  min_level: 1
  max_level: 1
  item_prefix: toc-
  sublist_class: ''
  ordered_list: true
  item_class: toc-entry
  list_class: section-nav
  no_toc_section_class: no_toc_section

feed:
  excerpt_only: true
  posts_limit: 500

kramdown:
  hard_wrap: true

highlighter: rouge

exclude:
    - env
    - notebooks
    - venv

collections:
  recipes:
    output: true

og_image:
  output_dir: "assets/og-images"
  image: "assets/images/isaac.jpeg"
  domain: "eniola.wtf"
  canvas:
    background_color: "#EEEEEE"
  border_bottom:
      width: 20
      fill:
        - "#F9ED69"
        - "#F08A5D"
        - "#B83B5E"
        - "#6A2C70"
