name: Deploy Jekyll site to Netlify

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "netlify"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems

      - name: Install libvips
        env:
          DEBIAN_FRONTEND: noninteractive
        run:
          sudo apt-get install --fix-missing libvips tree

      - name: Display build directory
        run: tree -a -L 1000 ./_site

      - name: Build with Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
            publish-dir: './_site'
            production-branch: main
            production-deploy: true
            enable-commit-comment: true
            enable-pull-request-comment: false
            overwrites-pull-request-comment: true
            github-token: ${{ secrets.GITHUB_TOKEN }}
            deploy-message: "deployed from github actions"
        env:
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
